language: elixir
sudo: false
elixir:
  - 1.7
otp_release:
  - 20.0
  - 20.1
  - 20.2
  - 20.3
before_script:
  - mix deps.get --only test
script: mix coveralls.travis
notifications:
  recipients:
    - travis@coryodaniel.com
